const handleError = (socket, error) => {
  try {
    //
    console.error(error);
  } catch (err) {
    //
  }
};
